version: "3.9"

services:
  api:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    networks:
      - rag_net

networks:
  rag_net:
    driver: bridge